server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://100.86.212.63:5432/postgres
    username: postgres
    password: Wete8Vmj7yMEQCwz
  data:
    redis:
      host: 100.86.212.63
      port: 6379
      password:
      database: 0
  cache:
    type: redis
    redis:
      time-to-live: 30d
      cache-null-values: false
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: NEVER
    auto-startup: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: SRMAdminScheduler
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: true
    wait-for-jobs-to-complete-on-shutdown: true
jwt:
  secret-key: your_key # jwt签名加密秘钥
  expireTime: 15552000000 # jwt过期时间毫秒
jimmer:
  offset-optimizing-threshold: 10
  id-only-target-checking-level: ALL
  database-validation-mode: ERROR
  show-sql: true
  pretty-sql: true
  # You can enable the following configuration line `inline-sql-variables: true`,
  # restart the application and call some REST APIs again to see what happens
  inline-sql-variables: true
  client:
    ts:
      path: /ts.zip
    openapi:
      path: /openapi.yml
      ui-path: /openapi.html
      properties:
        info:
          title: SRM Admin
          description: 自动生成的api文档
          version: 1.0
sms:
  aliyun:
    accessKeyId:
    accessKeySecret:
    endpoint:
    signName:
  tencentCloud:
    secretId: 12
    secretKey: 312
    appId: 321
    signName: 32131
grpc:
  port: 50051
logbook:
  format:
    style: json
