spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.100.155:5433/postgres
    username: postgres
    password: 123456
  data:
    redis:
      host: 192.168.100.155
      port: 6379
      password:
      database: 0
jwt:
  secret-key: your_key # jwt签名加密秘钥
  expireTime: 7200000 # jwt过期时间毫秒
jimmer:
  offset-optimizing-threshold: 10
  id-only-target-checking-level: ALL
  database-validation-mode: ERROR
  show-sql: true
  pretty-sql: true
  # You can enable the following configuration line `inline-sql-variables: true`,
  # restart the application and call some REST APIs again to see what happens
  inline-sql-variables: true
  client:
    openapi:
      path: /openapi.yml
      ui-path: /openapi.html
      properties:
        info:
          title: My Web Service
          description: |
            Restore the DTO explosion that was 
            eliminated by server-side developers
          version: 1.0
